### ISSUE TITLE
Many major cities missing

### ISSUE THREAD

**Issue by grigerny** [Abhishaker17/Clocker#2]
For example, for India - New Delhi or Mumbai

**Comment by Abhishaker17** [comment]
Hey,

Currently, I am fetching timezones from the NSTimezone API which gives this restricted list. Will have to use an external API to include all the cities.

For your example, for the existing version; you can search for Kolkata in the preferences section. 

I am currently working on a version to allow custom labels for timezones which can be pretty handy in this situation.

**Comment by filippoferraris** [comment]
yes! Customise the labels would be very useful!

**Comment by Abhishaker17** [comment]
As the new version is under App Store review (which can take long), I have added an updated version under the Releases section for you guys. This release features the custom label functionality and few other changes. :)

**Comment by grigerny** [comment]
Great! Looking forward to it!

Gary Riger 
Founder at Thinklab Media 
646-791-6277
thinklabmedia.com 
@garyriger




On Mon, Dec 14, 2015 at 8:08 PM -0800, "Abhishek Banthia" <notifications@github.com> wrote:












As the new version is under App Store review (which can take long), I have added an updated version under the Releases section for you guys. This release features the custom label functionality and few other changes. :)

**Comment by Abhishaker17** [comment]
With the new version (1.2.1), city search uses Google API which includes all the major cities around the world. 

Closing this.
